SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE T 
LEFT JOIN ITEM_INFO P
ON T.PARENT_ITEM_ID = P.ITEM_ID
LEFT JOIN ITEM_INFO C
ON C.ITEM_ID=T.ITEM_ID
WHERE P.RARITY='RARE'
ORDER BY ITEM_ID DESC;